# Generated by Django 4.1.1 on 2022-09-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=250)),
                ('movie_description', models.TextField()),
                ('yearof_release', models.IntegerField()),
                ('movie_rating', models.IntegerField()),
                ('movie_tag', models.CharField(max_length=250)),
                ('movie_thumbnail', models.ImageField(upload_to='thumbnail')),
            ],
        ),
    ]
